logger:
  level: "info"
http:
  host: localhost
  port: 8080
  readTimeout: 10s
  writeTimeout: 10s
auth:
  refreshTokenTTL: 12h
  accessTokenTTL: 2h
  autoLogoffTime: 1h
redis:
  host: "localhost"
  port: 6379
pg:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "postgres"
  db: "postgres"
  sslmode: "disable"
